<<<<<<< HEAD
# Generated by Django 2.2.7 on 2020-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_numarasi', models.IntegerField()),
            ],
        ),
    ]
=======
# Generated by Django 2.2.7 on 2020-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_numarasi', models.IntegerField()),
            ],
        ),
    ]
>>>>>>> b0a72d6931da3780e2e803ea7df66840a7591c35
